### ISSUE TITLE
unknown image format (PNG)

### ISSUE THREAD

**Issue by ernsheong** [bamiaux/rez#12]
The code:
```go
outputImage = image.NewRGBA(image.Rect(0, 0, targetWidth, targetHeight))
err := rez.Convert(outputImage, img, rez.NewBilinearFilter())
if err != nil {
  return errors.Wrap(err, "Could not convert PNG image") // unknown image format
}
```

The image:
https://blokt.com/wp-content/uploads/2019/01/Screenshot-2019-01-11-at-15.21.20-610x409.png

What is not compatible about the image, which is PNG format? Is this a bug in `rez`?

**Comment by bamiaux** [comment]
Probably because input height is not even, I'm not sure

**Comment by codesoap** [comment]
I've encountered the same problem. I have taken a look at the code and am certain, that it is a bug. The error occurs here: https://github.com/bamiaux/rez/blob/29f4463c688b986c11f166b12734f69b58b5555f/image.go#L333

It occurs, because `rez` only handles the image types `YCbCr`, `RGBA`, `NRGBA` and `Gray`. This is by far not a complete list. The `github.com/nfnt/resize` package has a more complete implementation; note that there is even special handling for the default case: https://github.com/nfnt/resize/blob/83c6a9932646f83e3267f353373d47347b6036b2/resize.go#L111

**Comment by bamiaux** [comment]
This package is now quite old, and those image types, I guess, didn't exist at the time. It should be easy to add support to any planar image format, but this package was more a proof of concept for me, on whether we could generate & use inline asm in Go.
Today, I'm sure better options exist, so I'm going to archive this project.
